### ISSUE TITLE
Implement Encounter Tracker

### ISSUE THREAD

**Issue by JoshuaBelden** [JoshuaBelden/dmkit#6]
- [ ] Users should be able to select characters for the encounter
- [ ] Users should be able to search and select monsters for the encounter
- [ ] Users should be able to give a nickname to monsters

Encounter should include
    - All players
    - All monsters
    - Initiative for all creatures
    - Monster initiative is automatically rolled but overridable
    - Creatures ordered by initiative
    - Hitpoints for all creatures
    - Monster hitpoints are automatically rolled
    - Condition for each creature
    - Current Round
    - Current Initiative
    - Advance Initiative
